<?php

    session_start(); // Iniciando Sessão...

    $id_produto = $_GET['id']; // Variavel recebe o id do produto via metodo GET e cria uma sessão carrinho para ele...

    unset($_SESSION['carrinho'] [$id_produto]); // removendo o id da sessão carrinho, assimm removendo o produto do carrinho...


    header('location:carrinho.php'); // Redirecionando o usuario para o carrinho de compras novamente...

?>